# Generated by Django 6.0 on 2025-12-23 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id_account', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CHECKING', 'Checking Account'), ('WALLET', 'Digital Wallet'), ('CREDIT_CARD', 'Credit Card')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='users.users')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'constraints': [models.UniqueConstraint(fields=('id_user', 'type'), name='unique_account_per_user')],
            },
        ),
    ]
