# Generated by Django 6.0 on 2026-01-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('CHECKING', 'Conta Corrente'), ('SAVINGS', 'Conta Poupança'), ('CREDIT_CARD', 'Cartão de Crédito'), ('INVESTMENT', 'Investimentos'), ('CASH', 'Dinheiro'), ('OTHER', 'Outro')], default='CHECKING', max_length=20),
        ),
    ]
