# Generated by Django 6.0 on 2026-01-10 15:06

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_at'], 'verbose_name': 'Conta', 'verbose_name_plural': 'Contas'},
        ),
        migrations.AddField(
            model_name='account',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Cor em hexadecimal (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição/Observações'),
        ),
        migrations.AddField(
            model_name='account',
            name='icon',
            field=models.CharField(blank=True, default='wallet', help_text='Ícone da conta (ex: wallet, credit-card, piggy-bank)', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Inicial'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Atual'),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instituição Bancária'),
        ),
        migrations.AlterField(
            model_name='account',
            name='closing_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia do Fechamento'),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Limite de Crédito'),
        ),
        migrations.AlterField(
            model_name='account',
            name='due_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia do Vencimento'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome da Conta'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('CHECKING', 'Conta Corrente'), ('SAVINGS', 'Conta Poupança'), ('CREDIT_CARD', 'Cartão de Crédito'), ('INVESTMENT', 'Investimentos'), ('CASH', 'Dinheiro'), ('OTHER', 'Outro')], default='CHECKING', max_length=20, verbose_name='Tipo de Conta'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_account_name_per_user'),
        ),
    ]
