# Generated by Django 6.0 on 2026-01-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options_account_color_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='creditcardbill',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__lte', models.F('total_amount'))), name='paid_amount_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='creditcardbill',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_payment__lte', models.F('total_amount'))), name='minimum_payment_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='creditcardbill',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='paid_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='creditcardbill',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_payment__gte', 0)), name='minimum_payment_non_negative'),
        ),
    ]
