# Generated by Django 6.0 on 2026-01-11 19:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_creditcardbill_paid_amount_lte_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id_account',
            field=models.UUIDField(db_column='id_account', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='account',
            old_name='id_account',
            new_name='account',
        ),
    ]
