# Generated by Django 6.0 on 2026-01-14 14:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_id_account_and_more'),
        ('transactions', '0003_alter_transaction_id_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('id_payment', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.creditcardbill')),
                ('payment_account', models.ForeignKey(help_text='Conta de onde saiu o dinheiro para pagar a fatura', on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_payments', to='accounts.account')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_card_payment', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Pagamento de Fatura',
                'verbose_name_plural': 'Pagamentos de Faturas',
                'ordering': ['-paid_at'],
            },
        ),
    ]
