# Generated by Django 6.0 on 2026-01-02 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id_recurrence_rule', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=50)),
                ('next_execution', models.DateField()),
                ('max_executions', models.IntegerField(blank=True, null=True)),
                ('executions_count', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('direction', models.CharField(choices=[('IN', 'Income'), ('OUT', 'Expense')], max_length=50)),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='accounts.account')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='categories.category')),
                ('id_payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='payments.paymentmethod')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurrence Rule',
                'verbose_name_plural': 'Recurrence Rules',
                'constraints': [models.CheckConstraint(condition=models.Q(('max_executions__gt', 0)), name='max_executions_positive')],
            },
        ),
    ]
