# Generated by Django 6.0 on 2026-01-11 18:38

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_creditcardbill_paid_amount_lte_total_and_more'),
        ('categories', '0002_alter_category_options_category_color_and_more'),
        ('payments', '0004_remove_installmentplan_total_amount_max_limit_and_more'),
        ('recurrence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recurrencerule',
            name='max_executions_positive',
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='last_execution',
            field=models.DateField(blank=True, help_text='Data da última execução', null=True),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativa'), ('PAUSED', 'Pausada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='ACTIVE', help_text='Status da regra de recorrência', max_length=20),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='recurrencerule',
            constraint=models.CheckConstraint(condition=models.Q(('max_executions__gt', 0), ('max_executions__isnull', True), _connector='OR'), name='max_executions_positive_or_null'),
        ),
        migrations.AddConstraint(
            model_name='recurrencerule',
            constraint=models.CheckConstraint(condition=models.Q(('executions_count__gte', 0)), name='executions_count_non_negative'),
        ),
    ]
