# Generated by Django 6.0 on 2025-12-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_accounts_account'),
        ('categories', '0002_rename_categories_category'),
        ('payments', '0002_rename_installment_plans_installmentplan_and_more'),
        ('recurrence', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recurrence_rules',
            new_name='RecurrenceRule',
        ),
    ]
