# Generated by Django 6.0 on 2026-01-11 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_id_account_and_more'),
        ('categories', '0003_remove_category_unique_category_per_user_and_more'),
        ('payments', '0005_remove_paymentmethod_unique_payment_method_per_user_and_more'),
        ('recurrence', '0002_remove_recurrencerule_max_executions_positive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrencerule',
            name='id_account',
            field=models.ForeignKey(db_column='id_account_id', on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='accounts.account'),
        ),
        migrations.RenameField(
            model_name='recurrencerule',
            old_name='id_account',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='recurrencerule',
            name='id_category',
            field=models.ForeignKey(db_column='id_category_id', on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='categories.category'),
        ),
        migrations.RenameField(
            model_name='recurrencerule',
            old_name='id_category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='recurrencerule',
            name='id_payment_method',
            field=models.ForeignKey(db_column='id_payment_method_id', on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='payments.paymentmethod'),
        ),
        migrations.RenameField(
            model_name='recurrencerule',
            old_name='id_payment_method',
            new_name='payment_method',
        ),
        migrations.AlterField(
            model_name='recurrencerule',
            name='id_recurrence_rule',
            field=models.UUIDField(db_column='id_recurrence_rule', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='recurrencerule',
            old_name='id_recurrence_rule',
            new_name='recurrence_rule',
        ),
        migrations.AlterField(
            model_name='recurrencerule',
            name='id_user',
            field=models.ForeignKey(db_column='id_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='recurrencerule',
            old_name='id_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='recurrencerule',
            index=models.Index(fields=['user', 'status'], name='recurrence__id_user_67643f_idx'),
        ),
        migrations.AddIndex(
            model_name='recurrencerule',
            index=models.Index(fields=['next_execution'], name='recurrence__next_ex_6ee36a_idx'),
        ),
    ]
