# Generated by Django 6.0.2 on 2026-05-21 02:50

import accounts.models
import accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('USER', 'Usuário')], default='USER', max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.models.avatar_upload_path, verbose_name='Avatar')),
                ('phone', models.CharField(blank=True, help_text='Formato: (XX) XXXXX-XXXX ou (XX) XXXX-XXXX', max_length=20, null=True, validators=[accounts.validators.validate_brazilian_phone], verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
