# Generated by Django 6.0.2 on 2026-05-12 00:31

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Formato: (XX) XXXXX-XXXX ou (XX) XXXX-XXXX', max_length=20, null=True, validators=[accounts.validators.validate_brazilian_phone], verbose_name='Telefone'),
        ),
    ]
