# Generated by Django 6.0 on 2025-12-23 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='budgets',
            fields=[
                ('id_budget', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='users.users')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
            },
        ),
        migrations.CreateModel(
            name='budget_categories_limits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories_limits', to='categories.categories')),
                ('id_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories_limits', to='budgets.budgets')),
            ],
            options={
                'verbose_name': 'Budget Category Limit',
                'verbose_name_plural': 'Budget Category Limits',
            },
        ),
        migrations.AddConstraint(
            model_name='budgets',
            constraint=models.UniqueConstraint(fields=('id_user', 'period_type', 'period_start'), name='unique_budget_period'),
        ),
        migrations.AddConstraint(
            model_name='budget_categories_limits',
            constraint=models.CheckConstraint(condition=models.Q(('limit_amount__gt', 0)), name='limit_amount_positive'),
        ),
    ]
