# Generated by Django 6.0 on 2026-01-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='budgetcategorylimit',
            constraint=models.UniqueConstraint(fields=('id_budget', 'id_category'), name='unique_budget_category'),
        ),
    ]
