# Generated by Django 6.0 on 2025-12-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('categories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='budgets',
            new_name='Budget',
        ),
        migrations.RenameModel(
            old_name='budget_categories_limits',
            new_name='BudgetCategoryLimit',
        ),
    ]
