# Generated by Django 6.0 on 2026-01-11 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_created_at_budget_period_end_budget_status_and_more'),
        ('categories', '0003_remove_category_unique_category_per_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_period',
        ),
        migrations.RemoveConstraint(
            model_name='budgetcategorylimit',
            name='unique_budget_category',
        ),
        migrations.AlterField(
            model_name='budget',
            name='id_budget',
            field=models.UUIDField(db_column='id_budget', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='id_budget',
            new_name='budget',
        ),
        migrations.AlterField(
            model_name='budget',
            name='id_user',
            field=models.ForeignKey(db_column='id_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='id_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='budgetcategorylimit',
            name='id_budget',
            field=models.ForeignKey(db_column='id_budget_id', on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories_limits', to='budgets.budget'),
        ),
        migrations.RenameField(
            model_name='budgetcategorylimit',
            old_name='id_budget',
            new_name='budget',
        ),
        migrations.AlterField(
            model_name='budgetcategorylimit',
            name='id_category',
            field=models.ForeignKey(db_column='id_category_id', on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories_limits', to='categories.category'),
        ),
        migrations.RenameField(
            model_name='budgetcategorylimit',
            old_name='id_category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='budget',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'period_type', 'period_start'), name='unique_budget_period'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='period_end_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='budgetcategorylimit',
            constraint=models.UniqueConstraint(fields=('budget', 'category'), name='unique_budget_category'),
        ),
    ]
