# Generated by Django 6.0 on 2026-01-12 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_remove_budget_unique_budget_period_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'status'], name='budgets_bud_id_user_c3fe48_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['period_start', 'period_end'], name='budgets_bud_period__09f043_idx'),
        ),
    ]
