# Generated by Django 6.0 on 2026-01-12 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_budget_budgets_bud_id_user_c3fe48_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'period_type', 'period_start'], name='budgets_bud_id_user_bd4382_idx'),
        ),
    ]
