# Generated by Django 6.0 on 2026-01-13 22:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_budget_budgets_bud_id_user_bd4382_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategorylimit',
            name='limit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
