# Generated by Django 6.0 on 2025-12-22 05:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id_account', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CHECKING', 'Checking Account'), ('WALLET', 'Digital Wallet'), ('CREDIT_CARD', 'Credit Card')], max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='payment_methods',
            fields=[
                ('id_payment_method', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('requires_account', models.BooleanField(default=True)),
                ('allows_installments', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('PIX', 'Pix'), ('CASH', 'Cash')], default='PIX', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id_category', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('id_parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='infrastructure.categories')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='infrastructure.users')),
            ],
        ),
        migrations.CreateModel(
            name='installment_plans',
            fields=[
                ('id_installment_plan', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('installments', models.IntegerField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='infrastructure.accounts')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='infrastructure.categories')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='infrastructure.users')),
            ],
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id_transaction', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('direction', models.CharField(choices=[('IN', 'Income'), ('OUT', 'Expense')], max_length=3)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('BRL', 'Brazilian Real'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='BRL', max_length=3)),
                ('origin', models.CharField(choices=[('MANUAL', 'Manual'), ('RECURRENT', 'Recurrent'), ('INSTALLMENT', 'Installment')], max_length=20)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='infrastructure.categories')),
                ('id_installment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='infrastructure.installment_plans')),
                ('id_payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='infrastructure.payment_methods')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='infrastructure.users')),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id_tag', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='infrastructure.users')),
            ],
        ),
        migrations.CreateModel(
            name='recurrence_rules',
            fields=[
                ('id_recurrence_rule', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=50)),
                ('next_execution', models.DateField()),
                ('max_executions', models.IntegerField(blank=True, null=True)),
                ('executions_count', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('direction', models.CharField(choices=[('IN', 'Income'), ('OUT', 'Expense')], max_length=50)),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='infrastructure.accounts')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='infrastructure.categories')),
                ('id_payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='infrastructure.payment_methods')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='infrastructure.users')),
            ],
        ),
        migrations.AddField(
            model_name='payment_methods',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='infrastructure.users'),
        ),
        migrations.CreateModel(
            name='financial_goals',
            fields=[
                ('id_financial_goal', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('deadline', models.DateField()),
                ('strategy', models.CharField(choices=[('SAVING', 'Saving'), ('DEBT_PAYOFF', 'Debt Payoff')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=20)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to='infrastructure.users')),
            ],
        ),
        migrations.CreateModel(
            name='budgets',
            fields=[
                ('id_budget', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly')], max_length=20)),
                ('period_start', models.DateField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='infrastructure.users')),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='infrastructure.users'),
        ),
        migrations.CreateModel(
            name='budget_categories_limits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('id_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories_limits', to='infrastructure.budgets')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories_limits', to='infrastructure.categories')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('limit_amount__gt', 0)), name='limit_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='transaction_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_tags', to='infrastructure.tags')),
                ('id_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_tags', to='infrastructure.transactions')),
            ],
            options={
                'unique_together': {('id_transaction', 'id_tag')},
            },
        ),
        migrations.CreateModel(
            name='transaction_accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_accounts', to='infrastructure.accounts')),
                ('id_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_accounts', to='infrastructure.transactions')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['source', 'destination'])), name='valid_account_role')],
                'unique_together': {('id_transaction', 'id_account', 'role')},
            },
        ),
        migrations.AddConstraint(
            model_name='transactions',
            constraint=models.CheckConstraint(condition=models.Q(('direction__in', ['IN', 'OUT'])), name='valid_transaction_direction'),
        ),
        migrations.AddConstraint(
            model_name='transactions',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='tags',
            constraint=models.UniqueConstraint(fields=('id_user', 'name'), name='unique_tag_per_user'),
        ),
        migrations.AddConstraint(
            model_name='recurrence_rules',
            constraint=models.CheckConstraint(condition=models.Q(('max_executions__gt', 0)), name='max_executions_positive'),
        ),
        migrations.AddConstraint(
            model_name='installment_plans',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='total_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='installment_plans',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__lt', 10000)), name='total_amount_max_limit'),
        ),
        migrations.AddConstraint(
            model_name='installment_plans',
            constraint=models.CheckConstraint(condition=models.Q(('installments__gt', 0)), name='installments_positive'),
        ),
        migrations.AddConstraint(
            model_name='installment_plans',
            constraint=models.CheckConstraint(condition=models.Q(('installments__lte', 36)), name='installments_max_limit'),
        ),
        migrations.AddConstraint(
            model_name='financial_goals',
            constraint=models.CheckConstraint(condition=models.Q(('target_amount__gt', 0)), name='target_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='budgets',
            constraint=models.UniqueConstraint(fields=('id_user', 'period_type', 'period_start'), name='unique_budget_period'),
        ),
    ]
