# Generated by Django 6.0.4 on 2026-05-15 00:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='category',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Orçamento mensal para esta categoria (opcional)', max_digits=10),
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='#8A4FFF', help_text='Cor hexadecimal para identificar a categoria', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='📌', help_text='Emoji ou ícone para representar a categoria', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'Entrada'), ('expense', 'Saída')], default='expense', help_text='Tipo da categoria: Entrada ou Saída', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name')},
        ),
    ]
