# Generated by Django 6.0 on 2025-12-23 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id_category', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('id_parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.categories')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='users.users')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'constraints': [models.UniqueConstraint(fields=('id_user', 'name'), name='unique_category_per_user')],
            },
        ),
    ]
