# Generated by Django 6.0 on 2026-01-10 14:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['type', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Cor em formato hexadecimal (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='receipt', help_text='Nome do ícone (Font Awesome, Material Icons, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], default='OUT', help_text='Se a categoria é para entrada (renda) ou saída (despesa)', max_length=3),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id_parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
