# Generated by Django 6.0 on 2026-01-11 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_category_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_per_user',
        ),
        migrations.AlterField(
            model_name='category',
            name='id_category',
            field=models.UUIDField(db_column='id_category', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='category',
            old_name='id_category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='id_parent_category',
            field=models.ForeignKey(blank=True, db_column='id_parent_category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='categories.category'),
        ),
        migrations.RenameField(
            model_name='category',
            old_name='id_parent_category',
            new_name='parent_category',
        ),
        migrations.AlterField(
            model_name='category',
            name='id_user',
            field=models.ForeignKey(db_column='id_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='category',
            old_name='id_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_category_per_user'),
        ),
    ]
