# Generated by Django 6.0.4 on 2026-05-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Entrada'), ('expense', 'Saída')], max_length=10),
        ),
    ]
