# Generated by Django 6.0.2 on 2026-05-12 00:04

from django.db import migrations, models
from categories.models import Category


def migrate_categories_forward(apps, schema_editor):
    Transaction = apps.get_model('transactions', 'Transaction')
    CategoryModel = apps.get_model('categories', 'Category')
    
    # Get unique (user, category_name) pairs
    category_data = Transaction.objects.values('user', 'category').distinct()
    
    for data in category_data:
        user_id = data['user']
        cat_name = data['category']
        if cat_name:
            # Assume type
            cat_type = 'expense'
            if any(word in cat_name.lower() for word in ['salário', 'receita', 'income']):
                cat_type = 'income'
            
            # Create category for the user
            category, created = CategoryModel.objects.get_or_create(
                user_id=user_id,
                name=cat_name,
                defaults={'type': cat_type}
            )
            
            # Update transactions
            Transaction.objects.filter(user_id=user_id, category=cat_name).update(category_id=category.id)


def migrate_categories_reverse(apps, schema_editor):
    Transaction = apps.get_model('transactions', 'Transaction')
    
    # Revert to category names
    for transaction in Transaction.objects.all():
        transaction.category = transaction.category.name
        transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey('categories.Category', on_delete=models.PROTECT, related_name='transactions'),
        ),
        migrations.RunPython(migrate_categories_forward, migrate_categories_reverse),
    ]
