# Generated by Django 6.0.4 on 2026-05-15 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20260511_2104'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_user_id_cb8cb9_idx',
            old_name='transaction_user_id_a385c1_idx',
        ),
    ]
