# Generated by Django 6.0.2 on 2026-07-12 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense', 'Despesa'), ('income', 'Receita'), ('saving', 'Economia')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('tag', models.CharField(blank=True, default='', max_length=50)),
                ('recurrence', models.CharField(choices=[('none', 'Não repetir'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('yearly', 'Anual')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação do Calendário',
                'verbose_name_plural': 'Transações do Calendário',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='dash_calend_user_id_3692cb_idx'), models.Index(fields=['user', 'type'], name='dash_calend_user_id_45b086_idx')],
            },
        ),
    ]
