# Generated by Django 6.0.2 on 2026-07-30 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_calendar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('categories', models.JSONField(default=dict)),
                ('extras', models.JSONField(default=list)),
                ('total_planned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('divisor', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planejamento Mensal',
                'verbose_name_plural': 'Planejamentos Mensais',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
