# Generated by Django 6.0.4 on 2026-07-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_calendar', '0002_monthlybudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('expense', 'Despesa'), ('income', 'Receita'), ('saving', 'Economia'), ('card', 'Cartão')], max_length=10),
        ),
    ]
