# Generated by Django ...
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_calendar', '0003_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_recurrence_instance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recurrence_parent',
        ),
    ]