# Generated by Django 6.0 on 2026-01-09 19:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id_financial_goal', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deadline', models.DateField()),
                ('strategy', models.CharField(choices=[('SAVE', 'Save'), ('INVEST', 'Invest'), ('SPEND', 'Spend'), ('DEBT_PAYOFF', 'Debt Payoff')], max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Goal',
                'verbose_name_plural': 'Financial Goals',
                'indexes': [models.Index(fields=['id_user', 'deadline'], name='goals_finan_id_user_b24c09_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_amount__gt', 0)), name='target_amount_positive')],
            },
        ),
    ]
