# Generated by Django 6.0 on 2025-12-23 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='financial_goals',
            fields=[
                ('id_financial_goal', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('deadline', models.DateField()),
                ('strategy', models.CharField(choices=[('SAVE', 'Save'), ('INVEST', 'Invest'), ('SPEND', 'Spend'), ('DEBT_PAYOFF', 'Debt Payoff')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to='users.users')),
            ],
            options={
                'verbose_name': 'Financial Goal',
                'verbose_name_plural': 'Financial Goals',
                'constraints': [models.CheckConstraint(condition=models.Q(('target_amount__gt', 0)), name='target_amount_positive')],
            },
        ),
    ]
