# Generated by Django 6.0 on 2026-01-11 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='financialgoal',
            name='goals_finan_id_user_b24c09_idx',
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='id_financial_goal',
            field=models.UUIDField(db_column='id_financial_goal', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='financialgoal',
            old_name='id_financial_goal',
            new_name='financial_goal',
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='id_user',
            field=models.ForeignKey(db_column='id_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='financialgoal',
            old_name='id_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='financialgoal',
            index=models.Index(fields=['user', 'deadline'], name='goals_finan_id_user_b24c09_idx'),
        ),
    ]
