# Generated by Django 6.0 on 2025-12-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='financial_goals',
            new_name='FinancialGoal',
        ),
    ]
