# Generated by Django 6.0 on 2026-01-05 15:41

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialgoal',
            name='status',
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='financialgoal',
            index=models.Index(fields=['id_user', 'deadline'], name='goals_finan_id_user_b24c09_idx'),
        ),
    ]
