# Generated by Django 6.0 on 2026-01-08 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_remove_financialgoal_status_financialgoal_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialgoal',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
