# Generated by Django 6.0.5 on 2026-05-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0002_add_bank_statement_import'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='importhistory',
            new_name='import_expo_user_id_5c7bc1_idx',
            old_name='import_exp_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='importhistory',
            new_name='import_expo_user_id_b44c77_idx',
            old_name='import_exp_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionimportmetadata',
            new_name='import_expo_fitid_3b21b5_idx',
            old_name='import_exp_fitid_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionimportmetadata',
            new_name='import_expo_documen_637021_idx',
            old_name='import_exp_document_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionimportmetadata',
            new_name='import_expo_import__c98ef1_idx',
            old_name='import_exp_import_idx',
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='error_message',
            field=models.TextField(blank=True, help_text='Descrição do erro geral', null=True),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='file_format',
            field=models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF'), ('ofx', 'OFX'), ('bbt', 'BBT (Banco do Brasil)'), ('txt', 'TXT'), ('json', 'JSON')], max_length=10),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='records_failed',
            field=models.IntegerField(default=0, help_text='Transações com erro de validação'),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='records_imported',
            field=models.IntegerField(default=0, help_text='Transações salvas com sucesso'),
        ),
    ]
