# Generated by Django 6.0 on 2025-12-23 16:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='installment_plans',
            fields=[
                ('id_installment_plan', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('installments', models.IntegerField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='accounts.accounts')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='categories.categories')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='users.users')),
            ],
            options={
                'verbose_name': 'Installment Plan',
                'verbose_name_plural': 'Installment Plans',
                'constraints': [models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='total_amount_positive'), models.CheckConstraint(condition=models.Q(('total_amount__lt', 10000)), name='total_amount_max_limit'), models.CheckConstraint(condition=models.Q(('installments__gt', 0)), name='installments_positive'), models.CheckConstraint(condition=models.Q(('installments__lte', 36)), name='installments_max_limit')],
            },
        ),
        migrations.CreateModel(
            name='payment_methods',
            fields=[
                ('type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('PIX', 'Pix'), ('CASH', 'Cash')], default='PIX', max_length=10)),
                ('id_payment_method', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('requires_account', models.BooleanField(default=True)),
                ('allows_installments', models.BooleanField(default=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='users.users')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'constraints': [models.UniqueConstraint(fields=('id_user', 'type', 'description'), name='unique_payment_method_per_user')],
            },
        ),
    ]
