# Generated by Django 6.0 on 2025-12-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_accounts_account'),
        ('categories', '0002_rename_categories_category'),
        ('payments', '0001_initial'),
        ('recurrence', '0001_initial'),
        ('transactions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='installment_plans',
            new_name='InstallmentPlan',
        ),
        migrations.RenameModel(
            old_name='payment_methods',
            new_name='PaymentMethod',
        ),
    ]
