# Generated by Django 6.0 on 2026-01-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(choices=[('CREDIT', 'Cartão de Crédito'), ('DEBIT', 'Cartão de Débito'), ('PIX', 'PIX'), ('CASH', 'Dinheiro'), ('BANK_TRANSFER', 'Transferência Bancária'), ('BOLETO', 'Boleto'), ('CRYPTO', 'Criptomoeda'), ('OTHER', 'Outro')], default='PIX', max_length=20),
        ),
    ]
