# Generated by Django 6.0 on 2026-01-11 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options_account_color_and_more'),
        ('categories', '0002_alter_category_options_category_color_and_more'),
        ('payments', '0002_alter_paymentmethod_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Taxa de juros mensal em % (0 para sem juros)', max_digits=5),
        ),
        migrations.AddConstraint(
            model_name='installmentplan',
            constraint=models.CheckConstraint(condition=models.Q(('interest_rate__gte', 0)), name='interest_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='installmentplan',
            constraint=models.CheckConstraint(condition=models.Q(('interest_rate__lte', 100)), name='interest_rate_max_100'),
        ),
    ]
