# Generated by Django 6.0 on 2026-01-11 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_creditcardbill_paid_amount_lte_total_and_more'),
        ('categories', '0002_alter_category_options_category_color_and_more'),
        ('payments', '0003_installmentplan_interest_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='installmentplan',
            name='total_amount_max_limit',
        ),
        migrations.RemoveConstraint(
            model_name='installmentplan',
            name='installments_max_limit',
        ),
        migrations.AddConstraint(
            model_name='installmentplan',
            constraint=models.CheckConstraint(condition=models.Q(('installments__lte', 360)), name='installments_max_limit'),
        ),
    ]
