# Generated by Django 6.0 on 2026-01-11 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_installmentplan_total_amount_max_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentmethod',
            name='unique_payment_method_per_user',
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='id_account',
            field=models.ForeignKey(db_column='id_account_id', on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='accounts.account'),
        ),
        migrations.RenameField(
            model_name='installmentplan',
            old_name='id_account',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='id_category',
            field=models.ForeignKey(db_column='id_category_id', on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='categories.category'),
        ),
        migrations.RenameField(
            model_name='installmentplan',
            old_name='id_category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='id_installment_plan',
            field=models.UUIDField(db_column='id_installment_plan', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='installmentplan',
            old_name='id_installment_plan',
            new_name='installment_plan',
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='id_user',
            field=models.ForeignKey(db_column='id_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='installmentplan',
            old_name='id_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='id_payment_method',
            field=models.UUIDField(db_column='id_payment_method', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='id_payment_method',
            new_name='payment_method',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='id_user',
            field=models.ForeignKey(db_column='id_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='id_user',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('user', 'type', 'description'), name='unique_payment_method_per_user'),
        ),
    ]
