# Generated by Django 6.0 on 2026-01-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_paymentmethod_unique_payment_method_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
