# Generated by Django 6.0.5 on 2026-05-16 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('monthly', 'Relatório Mensal'), ('quarterly', 'Relatório Trimestral'), ('yearly', 'Relatório Anual'), ('custom', 'Personalizado')], max_length=20)),
                ('format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('csv', 'CSV')], default='html', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-created_at'],
            },
        ),
    ]
