# Generated by Django 6.0 on 2025-12-23 16:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('payments', '0001_initial'),
        ('tags', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id_transaction', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('direction', models.CharField(choices=[('IN', 'Income'), ('OUT', 'Expense')], max_length=3)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('BRL', 'Brazilian Real'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='BRL', max_length=3)),
                ('origin', models.CharField(choices=[('MANUAL', 'Manual'), ('RECURRENT', 'Recurrent'), ('INSTALLMENT', 'Installment')], max_length=20)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='categories.categories')),
                ('id_installment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.installment_plans')),
                ('id_payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment_methods')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.users')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='transaction_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_tags', to='tags.tags')),
                ('id_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_tags', to='transactions.transactions')),
            ],
            options={
                'verbose_name': 'Transaction Tag',
                'verbose_name_plural': 'Transaction Tags',
            },
        ),
        migrations.CreateModel(
            name='transaction_accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_accounts', to='accounts.accounts')),
                ('id_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_accounts', to='transactions.transactions')),
            ],
            options={
                'verbose_name': 'Transaction Account',
                'verbose_name_plural': 'Transaction Accounts',
            },
        ),
        migrations.AddConstraint(
            model_name='transactions',
            constraint=models.CheckConstraint(condition=models.Q(('direction__in', ['IN', 'OUT'])), name='valid_transaction_direction'),
        ),
        migrations.AddConstraint(
            model_name='transactions',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='amount_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction_tags',
            unique_together={('id_transaction', 'id_tag')},
        ),
        migrations.AddConstraint(
            model_name='transaction_accounts',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['source', 'destination'])), name='valid_account_role'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction_accounts',
            unique_together={('id_transaction', 'id_account', 'role')},
        ),
    ]
