# Generated by Django 6.0 on 2026-01-09 19:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('payments', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('direction', models.CharField(choices=[('IN', 'Income'), ('OUT', 'Expense')], max_length=3)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('BRL', 'Brazilian Real'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='BRL', max_length=3)),
                ('origin', models.CharField(choices=[('MANUAL', 'Manual'), ('RECURRENT', 'Recurrent'), ('INSTALLMENT', 'Installment')], max_length=20)),
                ('description', models.CharField(blank=True, help_text='Descrição da transação', max_length=255, null=True)),
                ('installment_number', models.IntegerField(blank=True, help_text='Número da parcela (apenas para parcelamentos)', null=True)),
                ('total_installments', models.IntegerField(blank=True, help_text='Total de parcelas (apenas para parcelamentos)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_from', to='accounts.account')),
                ('account_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_to', to='accounts.account')),
                ('credit_card_bill', models.ForeignKey(blank=True, help_text='Fatura do cartão de crédito onde esta transação será incluída', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.creditcardbill')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='categories.category')),
                ('id_installment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.installmentplan')),
                ('id_payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.paymentmethod')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('source', 'Source Account'), ('destination', 'Destination Account')], default='source', max_length=20)),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_accounts', to='accounts.account')),
                ('id_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_accounts', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Transaction Account',
                'verbose_name_plural': 'Transaction Accounts',
            },
        ),
        migrations.CreateModel(
            name='TransactionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_tags', to='tags.tag')),
                ('id_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_tags', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Transaction Tag',
                'verbose_name_plural': 'Transaction Tags',
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('direction__in', ['IN', 'OUT'])), name='valid_transaction_direction'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('installment_number__isnull', True), ('installment_number__gt', 0), _connector='OR'), name='valid_installment_number'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('total_installments__isnull', True), ('total_installments__gt', 0), _connector='OR'), name='valid_total_installments'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('installment_number__isnull', True), ('total_installments__isnull', True), ('installment_number__lte', models.F('total_installments')), _connector='OR'), name='installment_number_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='transactionaccount',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['source', 'destination'])), name='valid_account_role'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionaccount',
            unique_together={('id_transaction', 'id_account', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='transactiontag',
            unique_together={('id_transaction', 'id_tag')},
        ),
    ]
