# Generated by Django 6.0 on 2025-12-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_accounts_account'),
        ('categories', '0002_rename_categories_category'),
        ('payments', '0002_rename_installment_plans_installmentplan_and_more'),
        ('tags', '0002_rename_tags_tag'),
        ('transactions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transactions',
            new_name='Transaction',
        ),
        migrations.RenameModel(
            old_name='transaction_accounts',
            new_name='TransactionAccount',
        ),
        migrations.RenameModel(
            old_name='transaction_tags',
            new_name='TransactionTag',
        ),
    ]
