# Generated by Django 6.0 on 2026-01-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_options_tag_color_tag_created_at_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account_from',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account_to',
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(related_name='transactions', through='transactions.TransactionTag', to='tags.tag'),
        ),
    ]
