# Generated by Django 6.0 on 2026-01-08 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('payments', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, help_text='Descrição da transação', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_number',
            field=models.IntegerField(blank=True, help_text='Número da parcela (apenas para parcelamentos)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_installments',
            field=models.IntegerField(blank=True, help_text='Total de parcelas (apenas para parcelamentos)', null=True),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('installment_number__isnull', True), ('installment_number__gt', 0), _connector='OR'), name='valid_installment_number'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('total_installments__isnull', True), ('total_installments__gt', 0), _connector='OR'), name='valid_total_installments'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('installment_number__isnull', True), ('total_installments__isnull', True), ('installment_number__lte', models.F('total_installments')), _connector='OR'), name='installment_number_lte_total'),
        ),
    ]
