# Generated by Django 6.0 on 2026-01-11 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_id_account_and_more'),
        ('tags', '0003_remove_tag_unique_tag_per_user_alter_tag_id_tag_and_more'),
        ('transactions', '0002_remove_transaction_account_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id_category',
            field=models.ForeignKey(db_column='id_category_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='categories.category'),
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='id_category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_installment_plan',
            field=models.ForeignKey(blank=True, db_column='id_installment_plan_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.installmentplan'),
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='id_installment_plan',
            new_name='installment_plan',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_payment_method',
            field=models.ForeignKey(db_column='id_payment_method_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.paymentmethod'),
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='id_payment_method',
            new_name='payment_method',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_transaction',
            field=models.UUIDField(db_column='id_transaction', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='id_transaction',
            new_name='transaction',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_user',
            field=models.ForeignKey(db_column='id_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='id_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='transactionaccount',
            name='id_account',
            field=models.ForeignKey(db_column='id_account_id', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_accounts', to='accounts.account'),
        ),
        migrations.RenameField(
            model_name='transactionaccount',
            old_name='id_account',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='transactionaccount',
            name='id_transaction',
            field=models.ForeignKey(db_column='id_transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_accounts', to='transactions.transaction'),
        ),
        migrations.RenameField(
            model_name='transactionaccount',
            old_name='id_transaction',
            new_name='transaction',
        ),
        migrations.AlterField(
            model_name='transactiontag',
            name='id_tag',
            field=models.ForeignKey(db_column='id_tag_id', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_tags', to='tags.tag'),
        ),
        migrations.RenameField(
            model_name='transactiontag',
            old_name='id_tag',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='transactiontag',
            name='id_transaction',
            field=models.ForeignKey(db_column='id_transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_tags', to='transactions.transaction'),
        ),
        migrations.RenameField(
            model_name='transactiontag',
            old_name='id_transaction',
            new_name='transaction',
        ),
        migrations.AlterUniqueTogether(
            name='transactionaccount',
            unique_together={('transaction', 'account', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='transactiontag',
            unique_together={('transaction', 'tag')},
        ),
    ]
