# Generated by Django 6.0 on 2026-01-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_id_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('PURCHASE', 'Compra'), ('PAYMENT', 'Pagamento'), ('TRANSFER', 'Transferência'), ('INCOME', 'Receita'), ('EXPENSE', 'Despesa'), ('CREDIT_CARD_PAYMENT', 'Pagamento de Cartão')], default='EXPENSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='direction',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], default='OUT', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='origin',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('INSTALLMENT', 'Parcelado'), ('RECURRENT', 'Recorrente')], default='MANUAL', max_length=20),
        ),
    ]
