# Generated by Django 6.0 on 2026-01-22 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_creditcardpayment'),
        ('transactions', '0004_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-occurred_at'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit_card_bill',
            field=models.ForeignKey(blank=True, help_text='Fatura do cartão de crédito onde esta transação será incluída', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_transactions', to='accounts.creditcardbill'),
        ),
    ]
