# Generated by Django 6.0 on 2025-12-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_accounts_account'),
        ('budgets', '0002_rename_budgets_budget_and_more'),
        ('categories', '0002_rename_categories_category'),
        ('goals', '0002_rename_financial_goals_financialgoal'),
        ('payments', '0002_rename_installment_plans_installmentplan_and_more'),
        ('recurrence', '0002_rename_recurrence_rules_recurrencerule'),
        ('tags', '0002_rename_tags_tag'),
        ('transactions', '0002_rename_transactions_transaction_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
    ]
